#index:
#    path: /
#    controller: App\Controller\DefaultController::index
filter_users_by_interest:
    path: /filter-users-by-interest
    controller: App\Controller\UserController::filterUsersByInterest
    methods: [POST]
